import androidx.compose.ui.graphics.Color

val PrimaryDark = Color(0xFF7AD7C6)
val OnPrimaryDark = Color(0xFF003830)
val PrimaryContainerDark = Color(0xFF00796B)
val BackgroundDark = Color(0xFF0E1417)
val SurfaceDark = Color(0xFF0E1417)
val SurfaceContainerLowDark = Color(0xFF161C1F)
val SurfaceContainerDark = Color(0xFF1A2024)
val SurfaceContainerHighestDark = Color(0xFF303639)
val SurfaceContainerLowestDark = Color(0xFF090F12)
val TextPrimaryDark = Color(0xFFDEE3E7)
val TextSecondaryDark = Color(0xFFBDC9C5)
val OutlineVariantDark = Color(0xFF3E4946)
val ErrorDark = Color(0xFFFFB4AB)
val SurfaceBrightDark = Color(0xFF343A3D)


val PrimaryLight = Color(0xFF006A60)
val OnPrimaryLight = Color(0xFFFFFFFF)
val PrimaryContainerLight = Color(0xFF7AD7C6)
val BackgroundLight = Color(0xFFF6F9F8)
val SurfaceLight = Color(0xFFF6F9F8)
val SurfaceContainerLowLight = Color(0xFFEFF3F1)
val SurfaceContainerLight = Color(0xFFE5EBE9)
val SurfaceContainerHighestLight = Color(0xFFDDE4E1)
val SurfaceContainerLowestLight = Color(0xFFFFFFFF)
val TextPrimaryLight = Color(0xFF161C1F)
val TextSecondaryLight = Color(0xFF50605D)
val OutlineVariantLight = Color(0xFFBFC9C5)
val ErrorLight = Color(0xFFBA1A1A)
val SurfaceBrightLight = Color(0xFFF0F5F3)